version: "3.1"

services:
  fake_s3:
    image: lphoward/fake-s3
    ports:
      - 4569:4569

  # https://hub.docker.com/_/microsoft-azure-storage-azurite
  fake_azure:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000

