version: "3.1"

services:
  fake_s3:
    image: lphoward/fake-s3
    ports:
      - 4569:4569

  # https://hub.docker.com/_/microsoft-azure-storage-azurite
  fake_azure:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000

  # https://github.com/fsouza/fake-gcs-server
  fake_gcs:
    image: fsouza/fake-gcs-server
    ports:
      - 4443:4443
    command: ["-scheme", "http", "-port", "4443", "-external-url", "http://localhost:4443", "-backend", "memory"]
