import { AddManyAction } from '../../src'
import { clear, scaffolder } from '../setup'

describe('AddManyAction', () => {
  beforeEach(clear)
  afterEach(clear)

  describe('execute', () => {
    it('should execute action correctly', async () => {
      const action = new AddManyAction({
        patterns: ['**/*'],
        from: './static',
        to: './',
        parameters: {
          project: {
            name: 'Test'
          }
        }
      })

      await action.execute(scaffolder)

      expect(await scaffolder.destination.exists('.gitignore')).toBeTruthy()
      expect(await scaffolder.destination.exists('README.md')).toBeTruthy()
      expect(await scaffolder.destination.get('README.md')).toMatchInlineSnapshot(`
        "# Test

        Generated by \`@apoyo/scaffold\`
        "
      `)
    })
  })
})
