import { CopyFilesAction } from '../../src'
import { clear, scaffolder } from '../setup'

describe('CopyFilesAction', () => {
  beforeEach(clear)
  afterEach(clear)

  describe('execute', () => {
    it('should execute action correctly', async () => {
      const action = new CopyFilesAction({
        patterns: ['**/*'],
        from: './static',
        to: './'
      })

      await action.execute(scaffolder)

      expect(await scaffolder.destination.exists('.gitignore')).toBeTruthy()
      expect(await scaffolder.destination.exists('README.md')).toBeTruthy()
      expect(await scaffolder.destination.get('README.md')).toMatchInlineSnapshot(`
        "# Test

        Generated by \`@apoyo/scaffold\`
        "
      `)
    })
  })
})
