name: Node.js CI - Publish

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn --frozen-lockfile
    - run: yarn build
    - run: yarn test
    - run: |
        npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        yarn pub:ci
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
