name: Node.js CI - Publish

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
          cache: yarn

      - run: yarn install --immutable

      - run: yarn build

      - run: yarn test
        env:
          AWS_S3_SERVER: fake_s3:4569

      - name: Publish
        run: yarn workspaces foreach --no-private npm publish --tolerate-republish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    services:
      fake_s3:
        image: lphoward/fake-s3
        ports:
          - 4569:4569