name: Node.js CI - PR

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    services:
      fake_s3:
        image: lphoward/fake-s3
        ports:
          - 4569:4569
      fake_azure:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
      fake_gcs:
        image: fsouza/fake-gcs-server
        ports:
          - 4443:4443
        # command: ["-scheme", "http", "-port", "4443", "-external-url", "http://localhost:4443", "-backend", "memory"]

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - run: yarn install --immutable

      - run: yarn build

      - run: yarn test
        env:
          AWS_S3_SERVER: http://localhost:4569
