name: Node.js CI - PR

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - run: yarn install --immutable

      - run: yarn lint

      - name: Build affected packages
        run: |
          git fetch origin master
          yarn jill each build --no-private --affected origin/master

      - run: docker-compose up -d

      - name: Test affected packages
        run: |
          git fetch origin master
          yarn jill each test --no-private --affected origin/master

      - run: docker-compose down

